### PR TITLE
Update for upstream schema changes

### PR DESCRIPTION
**Pull request by wfdd**
This creates a record per membership, though only the last two
legislative periods are complete.

### CODE REVIEW

**Comment by wfdd** [comment]
We've now got the new parliament's MPs.  Let me know if you want me to filter out earlier legislative periods.

**Comment by wfdd** [comment]
I'm assuming this might also necessitate some changes to the instructions file, for the legislative periods to be passed on down the pipeline.

**Comment by tmtmtmtm** [comment]
I can filter out the historic periods easily enough at the EP import stage (though would be good to get to the point where we can actually include them), but this seems to be losing a lot of data:

`select term, COUNT(DISTINCT(id)) FROM data WHERE term IN ("10", "11") GROUP BY term`

```
[
  {
    term: "10",
    COUNT(DISTINCT(id)): 57
  },
  {
    term: "11",
    COUNT(DISTINCT(id)): 28
  }
]
```

**Comment by wfdd** [comment]
huh.  Well, it's all there in the original data: 

``` py
In [7]: MP.collection.find({'tenures.parliamentary_period_id': '10'}).count()
Out[7]: 63

In [8]: MP.collection.find({'tenures.parliamentary_period_id': '11'}).count()
Out[8]: 56
```

**Comment by wfdd** [comment]
Ah, it's skipping all the records without a 'parliament.cy' source - the new MPs have been imported from [neavouli.eu](http://neavouli.eu).

**Comment by tmtmtmtm** [comment]
> it's skipping all the records without a 'parliament.cy' source 

I might be looking at the wrong thing here, but if you mean https://github.com/tmtmtmtm/cyprus-openpatata/blob/dbaf7d81bb33d0206637d3b91d906f2e6ef23df6/scraper.rb#L35, then that's not skipping those people, it's just not setting the 'source' column for them.

It's also a little odd that it's losing some people from the 10th period as well…

**Comment by wfdd** [comment]
It's skipping them on lines 37 to 39.

**Comment by wfdd** [comment]
Four MPs have the same ID, 259, because the script is picking the first source alphabetically.

**Comment by tmtmtmtm** [comment]
Ah, gotcha. That's going to be a little nasty to work around as we were using the parliament.cy IDs as the unique identifiers here. It's not particularly difficult, but it's more than 2 minutes work, so I'm going to have to leave it until later.

**Comment by wfdd** [comment]
> we were using the parliament.cy IDs as the unique identifiers here 

That sounds like a bad idea.  Those numbers are automatically generated by their CMS; just the other day, they moved former MPs to a different subpage and reset half the IDs in the process.

**Comment by tmtmtmtm** [comment]
Ah, the delights of unstable IDs. I've switched the scraper to use the openpatata IDs instead, but it'll require some fiddly work to re-reconcile those at the EveryPolitician end.

**Comment by wfdd** [comment]
For the record, they use people's names for cataloguing purposes.  The names are all unique.  If two or more people have the same name, they take on their father's first name as a middle name.

**Pull request merged**
